      SUBROUTINE FUEL
      INCLUDE 'Soldiv.fi'
C     CALCULATES NBI FUELING RATE AND PELLET FUELING EFFICIENCY

C           PELLET INJECTION EFFICIENCY (FIT TO DIII-D DATA)
      IF(PBEAM.LE.2.0) ETAPEL = 1.0
      IF(PBEAM.GT.2.0.AND.PBEAM.LE.8.0) ETAPEL = 
     2    1.0 - 0.5*((PBEAM-2.)/6.0)
      IF(PBEAM.GT.8.0) ETAPEL = 0.5
      SPELLET = ETAPEL*SPELLETREAL
      FUELMP = FUELMPREAL + (1.0 - ETAPEL)*SPELLETREAL 

C           FUELING DUE TO NBI
 50    IF(ENBI.EQ.0.0) GOTO 100
      SIGATTEN = AMU/(5.5E17*ENBI)
      X = .632*XNSEP*SIGATTEN*DELN/COS(PHIIN)
      FATTEN = 1. - EXP(-1.*X) 
      SPELLET = SPELLET + (0.625E22*PBEAM/ENBI)*(1. - FATTEN)
      FUELMP = FUELMP  + (0.625E22*PBEAM/ENBI)*FATTEN

 100   RETURN
      END